### ISSUE TITLE
Issues with picking up exported file

### ISSUE THREAD

**Issue by Nico-Mayer** [chkpwd/raycast-extensions-bak#2]
Hey, I experience an error while trying to import the `ente_auth.txt` and also on exporting it. I have set up the ente CLI and logged into my account. I can export the `ente_auth.txt` from the CLI no problem whatsoever, but when I try to import it with the extension, it won't work. Same for the export command. I tried multiple different export routes and made sure they are similar in the CLI and also the Raycast extension. I think that the extension has no rights to read or write to the file system.

Could you check on this error? If needed, I can provide more insights. 

Kind regards,
Nico

**Comment by chkpwd** [comment]
Hey @Nico-Mayer, thanks for using the extension, do you get a specific error while exporting/importhing? If so, please provide some screenshots.

**Comment by Nico-Mayer** [comment]
Hey @chkpwd, thanks for the fast reply. Here are some screenshots. Note that I tried a bunch of routes, also the default `~/Documents/ente`. 

<img width="426" alt="Bildschirmfoto 2024-11-24 um 03 21 09" src="https://github.com/user-attachments/assets/eb6e7542-a83f-401e-bf90-b10399dd5ba9">
<img width="230" alt="Bildschirmfoto 2024-11-24 um 03 20 59" src="https://github.com/user-attachments/assets/a5ac0f60-ce20-43f9-abde-e276930dcbd4">
<img width="361" alt="Bildschirmfoto 2024-11-24 um 03 20 32" src="https://github.com/user-attachments/assets/40cff412-1ad4-45a9-8ebb-83bf42c2436b">

**Comment by Nico-Mayer** [comment]
I looked into the code a bit and I think it may have something to do with how it resolves custom paths. I might add a PR in the next few days 😊

**Comment by chkpwd** [comment]
Hey @Nico-Mayer, I've fixed this issue and it will be available on the next release.
